---
title: "Lecture Slides"
output: 
  html_document:
    toc: TRUE
    toc_depth: 4
    toc_float: TRUE
    theme: cosmo
---

## Week 1

-   [R-Studio Intro](lectures/01_RStudio.pdf){target="_blank"}

## Week 2

-   [Open Science Overview](lectures/02_OpenScience.pdf){target="_blank"}

## Week 3

-   [Research Design & Data](lectures/03_ResearchDesign-Data.pdf){target="_blank"}

## Week 4

-   [Probability & Inferences](lectures/04_Probability-Inferencespdf){target="_blank"}

## Week 5

-   [Pre-Lab](lectures/05_Pre-Lab-speaker.html){target="_blank"}

-   [Hypotheses & Power](lectures/05_Hypothesis-Power-speaker.html){target="_blank"}

## Week 6

-   [Categorical Data](lectures/06_OneSample-speaker.html){target="_blank"}

-   [Categorical Data Part 2](lectures/06_OneSample2.html){target="_blank"}

## Week 7

-   [Comparing Means: t-test](lectures/07_ComparingMeans-speaker.html){target="_blank"}

## Week 8

-   [Dependent/Paired Samples t-test](lectures/08_ComparingMeans2.html){target="_blank"}

-   [Visualization (ggplot2)](lectures/08_Visualizations-speaker.html){target="_blank"}

## Week 9

-   [One-Way ANOVA](lectures/09_ANOVA-speaker.html){target="_blank"}

-   [ANOVA part 2](lectures/9_ANOVA2-speaker.html){target="_blank"}

## Week 10

-   [Correlation](lectures/10_Correlation-speaker.html){target="_blank"}

## Week 11

-   [Regression](lectures/11_Regression-speaker.html){target="_blank"}

-   [Regression part 2](lectures/12_Regression_pt2-speaker.html){target="_blank"}

## Next Week

-   [ ](lectures/.html){target="_blank"}

-   [ ](lectures/.html){target="_blank"}
