{
  "hash": "b9ef8801c1fc35638097d3ce80854ddd",
  "result": {
    "markdown": "---\ntitle: \"Introduction to ANOVA\"\nsubtitle: \"PSYC 640 - Fall 2023\"\nauthor: \"Dustin Haraden, PhD\"\nformat: \n  revealjs:\n    multiplex: true\n    scrollable: true\n    slide-number: true\n    incremental: false\n    touch: true\n    code-overflow: wrap\n    theme: dark\nexecute: \n  echo: true\neditor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Last Week\n\n::: nonincremental\n-   Comparing Means with 2 groups: $t$-test\n    -   Independent Samples $t$-test Review\n    -   Paired Samples $t$-test\n:::\n\n------------------------------------------------------------------------\n\n## Looking Ahead\n\n-   Plan to have 2 more labs that will be similar to the last lab\n\n    -   Likely take place on 10/25 and sometime the week of 11/13\n\n-   Outside of these labs, I am going to plan on having additional mini-labs\n\n    -   Likely to take place on 11/1, 11/22 and 11/29 (will update based on how things are going in class)\n\n------------------------------------------------------------------------\n\n## Today...\n\nIntroduction to ANOVA (Analysis of Variance)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# File management\nlibrary(here)\n# for dplyr, ggplot2\nlibrary(tidyverse)\n#Loading data\nlibrary(rio)\n\n#Remove Scientific Notation \noptions(scipen=999)\n```\n:::\n\n\n# Overview of ANOVA\n\n## What is ANOVA? ([LSR Ch. 14](https://learningstatisticswithr.com/book/anova.html))\n\n::: incremental\n-   ANOVA stands for [***An***]{.underline}alysis [***o***]{.underline}f [***Va***]{.underline}riance\n-   Comparing means between two or more groups (usually 3 or more)\n    -   Continuous outcome and grouping variable with 2 or more levels\n-   Under the larger umbrella of general linear models\n    -   ANOVA is basically a regression with only categorical predictors\n-   Likely the most widely used tool in Psychology\n:::\n\n## Different Types of ANOVA\n\n-   ::: {.fragment .highlight-green}\n    One-Way ANOVA\n    :::\n\n-   Two-Way ANOVA\n\n-   Repeated Measures ANOVA\n\n-   ANCOVA\n\n-   MANOVA\n\n## One-Way ANOVA\n\nGoal: Inform of differences among the levels of our variable of interest (Omnibus Test)\n\n-   But cannot tell us more than that...\n\nHypotheses:\n\n$$\nH_0: it\\: is\\: true\\: that\\: \\mu_1 = \\mu_2 = \\mu_3 =\\: ...\\mu_k \n\\\\ \nH_1: it\\: is\\: \\boldsymbol{not}\\: true\\: that\\: \\mu_1 = \\mu_2 = \\mu_3 =\\: ...\\mu_k\n$$\n\n## Wait...Means or Variance?\n\nWe are using the variance to create a ratio (within group versus between group variance) to determine differences in means\n\n-   We are not directly investigating variance, but operationalize variance to create the ratio:\n\n$$\nF_{df_b, \\: df_w} = \\frac{MS_{between}}{MS_{within}}\n$$\n\n------------------------------------------------------------------------\n\n![](/images/ANOVA.png){width=\"729\"}\n\n------------------------------------------------------------------------\n\n![](/images/ANOVA.png){width=\"729\"}\n\n::: columns\n::: {.column width=\"50%\"}\n$F = \\frac{MS_{between}}{MS_{within}} = \\frac{small}{large} < 1$\n:::\n\n::: {.column width=\"50%\"}\n$F = \\frac{MS_{between}}{MS_{within}} = \\frac{large}{small} > 1$\n:::\n:::\n\n## ANOVA: Assumptions\n\n::: {style=\"font-size: 30px\"}\n**Independence**\n\n-   Observations between and within groups should be independent. No autocorrelation\n\n**Homogeneity of Variance**\n\n-   The variances within each group should be roughly equal\n    -   Levene's test --\\> Welch's ANOVA for unequal variances\n\n**Normality**\n\n-   The data within each group should follow a normal distribution\n    -   Shapiro-Wilk test --\\> can transform the data or use non-parametric tests\n:::\n\n# NHST with ANOVA\n\n## Review of the NHST process\n\n::: incremental\n1.  Collect Sample and define hypotheses\n\n2.  Set alpha level\n\n3.  Determine the sampling distribution (will be using $F$-distribution now)\n\n4.  Identify the critical value\n\n5.  Calculate test statistic for sample collected\n\n6.  Inspect & compare statistic to critical value; Calculate probability\n:::\n\n## Steps to calculating F-ratio\n\n1.  Capture variance both between and within groups\n2.  Variance to Sum of Squares\n3.  Degrees of Freedom\n4.  Mean squares values\n5.  F-Statistic\n\n## Capturing Variance\n\nWe have calculated variance before!\n\n$$\nVar = \\frac{1}{N}\\sum(x_i - \\bar{x})^2\n$$\n\nNow we have to take into account the variance between and within the groups:\n\n$$\nVar(Y) = \\frac{1}{N} \\sum^G_{k=1}\\sum^{N_k}_{i=i}(Y_{ik} - \\bar{Y})^2\n$$\n\n::: {style=\"font-size: 20px; text-align: center\"}\nNotice that we have the summation across each group ( $G$ ) and the person in the group ( $N_k$ )\n:::\n\n------------------------------------------------------------------------\n\n## Variance to Sum of Squares\n\n**Total Sum of Squares -** Adding up the sum of squares instead of getting the average (notice the removal of $\\frac{1}{N}$)\n\n$$\nSS_{total} = \\sum^G_{k=1}\\sum^{N_k}_{i=i}(Y_{ik} - \\bar{Y})^2\n$$\n\nCan be broken up to see what is the variation ***between*** the groups AND the variation ***within*** the groups\n\n$$\nSS_{total}=SS_{between}+SS_{within}\n$$\n\n::: {style=\"font-size: 20px; text-align: center\"}\nThis gets us closer to understanding the difference between means\n:::\n\n# Sum of Squares\n\n------------------------------------------------------------------------\n\n### Sum of Squares\n\n$$\nSS_{total}=SS_{between}+SS_{within}\n$$\n\n![](/images/var_ss.PNG){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n### Example Data\n\n![](/images/table1.PNG){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n### Example Data\n\n![](/images/table2.PNG){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n### Example Data\n\n![](/images/table3.PNG){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n### Example Data\n\n![](/images/table4.PNG){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n## Sum of Squares - Between\n\nThe difference between the *group mean* and *grand mean*\n\n$$\nSS_{between} = \\sum^G_{k=1}N_k(\\bar{Y_k} - \\bar{Y})^2\n$$\n\n| Group  | Group Mean $\\bar{Y_k}$ | Grand Mean $\\bar{Y}$ |\n|:------:|:----------------------:|:--------------------:|\n|  Cool  |           32           |         41.8         |\n| Uncool |          56.5          |         41.8         |\n\n------------------------------------------------------------------------\n\n## Sum of Squares - Between\n\nThe difference between the *group mean* and *grand mean*\n\n$$ SS_{between} = \\sum^G_{k=1}N_k(\\bar{Y_k} - \\bar{Y})^2 $$\n\n| Group  | Group Mean $\\bar{Y_k}$ | Grand Mean $\\bar{Y}$ | Sq. Dev. |  N  | Weighted Sq. Dev. |\n|:------:|:----------------------:|:--------------------:|:--------:|:---:|:-----------------:|\n|  Cool  |           32           |         41.8         |  96.04   |  3  |      288.12       |\n| Uncool |          56.5          |         41.8         |  216.09  |  2  |      432.18       |\n\n------------------------------------------------------------------------\n\n## Sum of Squares - Between\n\nThe difference between the *group mean* and *grand mean*\n\n$$ SS_{between} = \\sum^G_{k=1}N_k(\\bar{Y_k} - \\bar{Y})^2 $$\n\nNow we can sum the Weighted Squared Deviations together to get our Sum of Squares Between:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nssb <- 288.12 + 432.18\nssb\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 720.3\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Sum of Squares - Within\n\nThe difference between the [*individual*]{.underline} and their [*group mean*]{.underline}\n\n$$\nSS_{within} = \\sum^G_{k=1}\\sum^{N_k}_{i=i}(Y_{ik} - \\bar{Y_k})^2\n$$\n\n|    Name    | Grumpiness $Y_{ik}$ | Group Mean $\\bar{Y_K}$ |\n|:----------:|:-------------------:|:----------------------:|\n|   Frodo    |         20          |           32           |\n|    Sam     |         55          |           32           |\n|   Bandit   |         21          |           32           |\n| Dolores U. |         91          |          56.5          |\n|   Dustin   |         22          |          56.5          |\n\n------------------------------------------------------------------------\n\n## Sum of Squares - Within\n\nThe difference between the [*individual*]{.underline} and their [*group mean*]{.underline}\n\n$$ SS_{within} = \\sum^G_{k=1}\\sum^{N_k}_{i=i}(Y_{ik} - \\bar{Y_k})^2 $$\n\n|    Name    | Grumpiness $Y_{ik}$ | Group Mean $\\bar{Y_K}$ | Sq. Dev |\n|:----------:|:-------------------:|:----------------------:|---------|\n|   Frodo    |         20          |           32           | 144     |\n|    Sam     |         55          |           32           | 529     |\n|   Bandit   |         21          |           32           | 121     |\n| Dolores U. |         91          |          56.5          | 1190.25 |\n|   Dustin   |         22          |          56.5          | 1190.25 |\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nscore <- c(20, 55, 21, 91, 22)\ngroup_m <- c(32, 32, 32, 56.5, 56.5)\nsq_dev <- (score - group_m)^2\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Sum of Squares - Within\n\nThe difference between the [*individual*]{.underline} and their [*group mean*]{.underline}\n\n$$ SS_{within} = \\sum^G_{k=1}\\sum^{N_k}_{i=i}(Y_{ik} - \\bar{Y_k})^2 $$ Now we can sum the Squared Deviations together to get our Sum of Squares Within:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(sq_dev)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3174.5\n```\n:::\n:::\n\n\n## Sum of Squares\n\nCan start to have an idea of what this looks like\n\n$$\nSS_{between} = \\sum^G_{k=1}N_k(\\bar{Y_k} - \\bar{Y})^2 = 720.3\n$$\n\n$$\nSS_{within} = \\sum^G_{k=1}\\sum^{N_k}_{i=i}(Y_{ik} - \\bar{Y_k})^2 = 3174.5\n$$\n\nNext we have to take into account the degrees of freedom\n\n# Degrees of Freedom - ANOVA\n\n------------------------------------------------------------------------\n\n## Degrees of Freedom\n\nSince we have 2 types of variations that we are examining, this needs to be reflected in the degrees of freedom\n\n1.  Take the number of groups and subtract 1\\\n    $df_{between} = G - 1$\n\n2.  Take the total number of observations and subtract the number of groups\\\n\n    $df_{within} = N - G$\n\n# Mean Squares\n\n------------------------------------------------------------------------\n\n## Calculating Mean Squares\n\nNext we convert our summed squares value into a \"mean squares\"\n\nThis is done by dividing by the respective degrees of freedom\n\n$$\nMS_b = \\frac{SS_b}{df_b}\n$$\n\n$$\nMS_W = \\frac{SS_w}{df_w}\n$$\n\n------------------------------------------------------------------------\n\n## Calculating Mean Squares - Example\n\nLet's take a look at how this applies to our example: $$ MS_b = \\frac{SS_b}{G-1} = \\frac{720.3}{2-1} = 720.3 $$\n\n$$ MS_W = \\frac{SS_w}{N-G} = \\frac{3174.5}{5-2} = 1058.167  $$\n\n# $F$-Statistic\n\n------------------------------------------------------------------------\n\n## Calculating the F-Statistic\n\n$$F = \\frac{MS_b}{MS_w}$$\n\nIf the null hypothesis is true, $F$ has an expected value close to 1 (numerator and denominator are estimates of the same variability)\n\nIf it is false, the numerator will likely be larger, because systematic, between-group differences contribute to the variance of the means, but not to variance within group.\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata.frame(F = c(0,8)) %>%\n  ggplot(aes(x = F)) +\n  stat_function(fun = function(x) df(x, df1 = 3, df2 = 196), \n                geom = \"line\") +\n  stat_function(fun = function(x) df(x, df1 = 3, df2 = 196), \n                geom = \"area\", xlim = c(2.65, 8), fill = \"purple\") +\n  geom_vline(aes(xintercept = 2.65), color = \"purple\") +\n  scale_y_continuous(\"Density\") + scale_x_continuous(\"F statistic\", breaks = NULL) +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](09_ANOVA_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\nIf data are normally distributed, then the variance is $\\chi^2$ distributed\n\n$F$-distributions are one-tailed tests. Recall that we're interested in how far away our test statistic from the null $(F = 1).$\n\n------------------------------------------------------------------------\n\n## Calculating F-statistic: Example\n\n$$F = \\frac{MS_b}{MS_w} = \\frac{720.3}{1058.167} = 0.68$$\n\n[Link](http://courses.atlas.illinois.edu/spring2016/STAT/STAT200/pf.html) to probability calculator\n\n------------------------------------------------------------------------\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndata.frame(F = c(0,8)) %>%\n  ggplot(aes(x = F)) +\n  stat_function(fun = function(x) df(x, df1 = 3, df2 = 196), \n                geom = \"line\") +\n  stat_function(fun = function(x) df(x, df1 = 3, df2 = 196), \n                geom = \"area\", xlim = c(2.65, 8), fill = \"purple\") +\n  geom_vline(aes(xintercept = 2.65), color = \"purple\") + \n  geom_vline(aes(xintercept = 0.68), color = \"red\") + \n  annotate(\"text\",\n           label = \"F=0.68\", \n           x = 1.1, y = 0.65, size = 8, color = \"red\") + \n  scale_y_continuous(\"Density\") + scale_x_continuous(\"F statistic\", breaks = NULL) +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](09_ANOVA_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\nWhat can we conclude?\n\n------------------------------------------------------------------------\n\n## Contrasts/Post-Hoc Tests\n\nPerformed when there is a significant difference among the groups to examine which groups are different\n\n1.  **Contrasts**: When we have *a priori* hypotheses\n2.  **Post-hoc Tests**: When we want to test everything\n\n# Reporting Results\n\n------------------------------------------------------------------------\n\n## Tables\n\nOften times the output will be in the form of a table and then it is often reported this way in the manuscript\n\n| Source of Variation |  df   | Sum of Squares |        Mean Squares        |       F-statistic       | p-value |\n|:-------------------:|:-----:|:--------------:|:--------------------------:|:-----------------------:|:-------:|\n|        Group        | $G-1$ |     $SS_b$     | $MS_b = \\frac{SS_b}{df_b}$ | $F = \\frac{MS_b}{MS_w}$ |   $p$   |\n|      Residual       | $N-G$ |     $SS_w$     | $MS_w = \\frac{SS_w}{df_w}$ |                         |         |\n|        Total        | $N-1$ |  $SS_{total}$  |                            |                         |         |\n\n------------------------------------------------------------------------\n\n## In-Text\n\n> A one-way analysis of variance was used to test for differences in the \\[variable of interest/outcome variable\\] as a function of \\[whatever the factor is\\]. Specifically, differences in \\[variable of interest\\] were assessed for the \\[list different levels and be sure to include (M= , SD= )\\] . The one-way ANOVA revealed a significant/nonsignificant effect of \\[factor\\] on scores on the \\[variable of interest\\] (F(dfb, dfw) = f-ratio, p = p-value, η2 = effect size).\n>\n> Planned comparisons were conducted to compare expected differences among the \\[however many groups\\] means. Planned contrasts revealed that participants in the \\[one of the conditions\\] had a greater/fewer \\[variable of interest\\] and then include the p-value. This same type of sentence is repeated for whichever contrasts you completed. Descriptive statistics were reported in Table 1.\n\n# Spooky Data Example\n\n------------------------------------------------------------------------\n\n## New Data Collection: Example\n\nWe want to be able to connect with the paranormal. Collected data at different locations to examine whether there are certain areas that have more ghost activity. We have multiple ratings (EMF) at the various locations to determine the potential presence of ghosts. The locations were determined by a select group of undergraduate researchers. They include:\n\n::: columns\n::: {.column width=\"50%\"}\n-   Walmart\n-   Abandoned Walmart\n-   Ikea\n-   Getysburg\n:::\n\n::: {.column width=\"50%\"}\n-   The Woods\n-   Unused Stairwell\n-   RIT Tunnels\n-   This classroom\n:::\n:::\n\n------------------------------------------------------------------------\n\n## Review of the NHST process\n\n::: incremental\n1.  Collect Sample and define hypotheses\n\n2.  Set alpha level\n\n3.  Determine the sampling distribution (will be using $F$-distribution now)\n\n4.  Identify the critical value\n\n5.  Calculate test statistic for sample collected\n\n6.  Inspect & compare statistic to critical value; Calculate probability\n:::\n\n------------------------------------------------------------------------\n\n## Example:\n\nTake a look at the data and compute the following:\n\n| Source of Variation |  df   | Sum of Squares |        Mean Squares        |       F-statistic       | p-value |\n|:-------------------:|:-----:|:--------------:|:--------------------------:|:-----------------------:|:-------:|\n|        Group        | $G-1$ |     $SS_b$     | $MS_b = \\frac{SS_b}{df_b}$ | $F = \\frac{MS_b}{MS_w}$ |   $p$   |\n|      Residual       | $N-G$ |     $SS_w$     | $MS_w = \\frac{SS_w}{df_w}$ |                         |         |\n|        Total        | $N-1$ |  $SS_{total}$  |                            |                         |         |\n\nCan use R or Excel\n\n# Next time...\n\n-   Two-Way ANOVA!\n",
    "supporting": [
      "09_ANOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    // dispatch for htmlwidgets\r\n    function fireSlideEnter() {\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n    }\r\n\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n      fireSlideEnter();\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}