{
  "hash": "adb8e5865df4f704c85c4317fb0b54af",
  "result": {
    "markdown": "---\ntitle: \"Comparing Means: Paired t-tests\"\nsubtitle: \"PSYC 640 - Fall 2023\"\nauthor: \"Dustin Haraden, PhD\"\nformat: \n  revealjs:\n    multiplex: true\n    slide-number: true\n    incremental: true\n    touch: true\n    code-overflow: wrap\n    theme: dark\nexecute: \n  echo: true\neditor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Last week\n\n::: nonincremental\n-   Comparing Means: $t$-test\n    -   Independent Samples $t$-test\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\n# File management\nlibrary(here)\n# for dplyr, ggplot\nlibrary(tidyverse)\n#Loading data\nlibrary(rio)\n# Assumption Checks\nlibrary(car)\n\n#Remove Scientific Notation \noptions(scipen=999)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Today...\n\n::: nonincremental\n-   Comparing Means with the $t$-test\n\n    ::: nonincremental\n    -   Paired Samples\n    :::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_school <- import(\"https://raw.githubusercontent.com/dharaden/dharaden.github.io/main/courses/PSYC640_fall23/data/NM-NY_CAS.csv\")\n```\n:::\n\n\n# Review: Independent $t$-test\n\n## Independent Samples $t$-test\n\n[Chapter 13.3 in Learning Stats with R](https://learningstatisticswithr.com/book/ttest.html#studentttest)\n\n::: columns\n::: {.column width=\"50%\"}\nTwo different types: Student's & Welch's\n\n::: nonincremental\n-   Student's $t$-test\n-   Welch's $t$-test\n:::\n:::\n\n::: {.column width=\"50%\"}\n$$\nt = \\frac{\\bar{X_1} - \\bar{X_2}}{SE(\\bar{X_1} - \\bar{X_2})}\n$$\n:::\n:::\n\n------------------------------------------------------------------------\n\n## Types of t-Tests: Assumptions\n\n~~Single Samples t-test~~\n\n~~Independent Samples t-test~~\n\n***Paired Samples t-test***\n\n-   Approximately normal distributions\n\n-   Homogeneity of variances\n\n-   ***Spoiler Alert! The same as a one-sample*** $t$***-test***\n\n------------------------------------------------------------------------\n\n## Steps for $t$-test\n\n1.  Check for normality of variables\n    -   Visualizing, Q-Q plots, Statistical Tests\n2.  Homogeneity of Variance\n    -   Levene's test --\\> Welch's $t$-test\n\n------------------------------------------------------------------------\n\n### Student's t-test: In R\n\n::: columns\n::: {.column width=\"50%\"}\n`independentSamplesTest()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindependentSamplesTTest(\n  formula = Sleep_Hours_Schoolnight ~ Region, \n  data = state_school, \n  var.equal = TRUE #default is FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Student's independent samples t-test \n\nOutcome variable:   Sleep_Hours_Schoolnight \nGrouping variable:  Region \n\nDescriptive statistics: \n               NM    NY\n   mean     6.989 6.994\n   std dev. 1.379 1.512\n\nHypotheses: \n   null:        population means equal for both groups\n   alternative: different population means in each group\n\nTest results: \n   t-statistic:  -0.024 \n   degrees of freedom:  180 \n   p-value:  0.981 \n\nOther information: \n   two-sided 95% confidence interval:  [-0.428, 0.418] \n   estimated effect size (Cohen's d):  0.004 \n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n`t.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  formula = Sleep_Hours_Schoolnight ~ Region, \n  data = state_school, \n  var.equal = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tTwo Sample t-test\n\ndata:  Sleep_Hours_Schoolnight by Region\nt = -0.023951, df = 180, p-value = 0.9809\nalternative hypothesis: true difference in means between group NM and group NY is not equal to 0\n95 percent confidence interval:\n -0.4281648  0.4178954\nsample estimates:\nmean in group NM mean in group NY \n        6.989247         6.994382 \n```\n:::\n:::\n\n:::\n:::\n\n------------------------------------------------------------------------\n\n### Welch's t-test: In R\n\n::: columns\n::: {.column width=\"50%\"}\n`independentSamplesTest()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindependentSamplesTTest(\n  formula = Sleep_Hours_Schoolnight ~ Region, \n  data = state_school, \n  var.equal = FALSE #This is what is different!\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Welch's independent samples t-test \n\nOutcome variable:   Sleep_Hours_Schoolnight \nGrouping variable:  Region \n\nDescriptive statistics: \n               NM    NY\n   mean     6.989 6.994\n   std dev. 1.379 1.512\n\nHypotheses: \n   null:        population means equal for both groups\n   alternative: different population means in each group\n\nTest results: \n   t-statistic:  -0.024 \n   degrees of freedom:  176.737 \n   p-value:  0.981 \n\nOther information: \n   two-sided 95% confidence interval:  [-0.429, 0.419] \n   estimated effect size (Cohen's d):  0.004 \n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n`t.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  formula = Sleep_Hours_Schoolnight ~ Region, \n  data = state_school, \n  var.equal = FALSE #This is what is different!\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  Sleep_Hours_Schoolnight by Region\nt = -0.023902, df = 176.74, p-value = 0.981\nalternative hypothesis: true difference in means between group NM and group NY is not equal to 0\n95 percent confidence interval:\n -0.4290776  0.4188082\nsample estimates:\nmean in group NM mean in group NY \n        6.989247         6.994382 \n```\n:::\n:::\n\n:::\n:::\n\n------------------------------------------------------------------------\n\n### Interpreting and writing up an independent samples t-test\n\n::: {style=\"font-size: 30px\"}\nThe first sentence usually conveys some descriptive information about the two groups you were comparing. Then you identify the type of test you conducted and what was determined (be sure to include the \"stat block\" here as well with the t-statistic, df, p-value, CI and Effect size). Finish it up by putting that into person words and saying what that means.\n:::\n\n> ::: {style=\"font-size: 30px\"}\n> The mean amount of sleep in New Mexico for youth was 6.989 (SD = 1.379), while the mean in New York was 6.994 (SD = 1.512). A Student's independent samples t-test showed that there was not a significant mean difference (*t*(180)=-0.024, *p*=.981, $CI_{95}$=\\[-0.43, 0.42\\], *d*=.004). This suggests that there is no difference between youth in NM and NY on amount of sleep on school nights.\n> :::\n\n# Today: Paired Samples\n\n## Paired Samples $t$-Test\n\n[Chapter 13.5 - Learning Stats with R](https://learningstatisticswithr.com/book/ttest.html#pairedsamplesttest)\n\nAlso called \"Dependent Samples t-test\"\n\n-   We have been testing means between two *independent* samples. Participants may be randomly assigned to the separate groups\n\n    -   This is limited to those types of study designs, but what if we have repeated measures?\n\n-   We will then need to compare scores across people...the samples we are comparing now *depend* on one another and are *paired*\n\n------------------------------------------------------------------------\n\n### Paired Samples $t$-test\n\nEach of the repeated measures (or pairs) can be viewed as a *difference score*\n\nThis reduces the analysis to a one-sample t-test of the *difference score*\n\n-   We are comparing the sample (i.e., difference scores) to a population $\\mu$ = 0\n\n------------------------------------------------------------------------\n\n### Assumptions: Paired Samples\n\nThe variable of interest (*difference scores*):\n\n-   Continuous (Interval/Ratio)\n\n-   Have 2 groups (and only two groups) that are matched\n\n-   Normally Distributed\n\n------------------------------------------------------------------------\n\n### Why paired samples??\n\nPreviously, we looked at independent samples $t$-tests, which we *could* do here as well (nobody will yell at you)\n\n-   However, this would violate the assumption that the data points are independent of one another!\n\n-   Within vs. Between-subjects\n\n------------------------------------------------------------------------\n\n### Within vs. Between Subjects\n\n![](/images/between-subjects-design.avif){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n### Paired Samples: Single Sample\n\nInstead of focusing on these variables as being separate/independent, we need to be able to account for their dependency on one another\n\nThis is done by calculating a *difference* or *change* score for each participant\n\n$$ D_i = X_{i1} - X_{i2} $$\n\nNotice: The equation is set up as `variable1` minus `variable2`. This will be important when we interpret the results\n\n------------------------------------------------------------------------\n\n### Paired Samples: Hypotheses & $t$-statistic\n\nThe hypotheses would then be:\n\n$$ H_0:  \\mu_D = 0; H_1: \\mu_D \\neq 0 $$\n\nAnd to calculate our t-statistic:       $t_{df=n-1} = \\frac{\\bar{D}}{SE(D)}$\n\nwhere the Standard Error of the difference score is:        $\\frac{\\hat{\\sigma_D}}{\\sqrt{N}}$\n\n------------------------------------------------------------------------\n\n## Review of the t-test process\n\n1.  Collect Sample and define hypotheses\n\n2.  Set alpha level\n\n3.  Determine the sampling distribution ($t$ distribution for now)\n\n4.  Identify the critical value that corresponds to alpha and *df*\n\n5.  Calculate test statistic for sample collected\n\n6.  Inspect & compare statistic to critical value; Calculate probability\n\n# Example 1: Simple\n\nParticipants are placed in two differently colored rooms and are asked to rate overall happiness levels after each\n\nHypotheses:\n\n-   $H_0:$ There is no difference in ratings of happiness between the rooms ( $\\mu = 0$ )\n\n-   $H_1:$ There is a difference in ratings of happiness between the rooms ( $\\mu \\neq 0$ )\n\n------------------------------------------------------------------------\n\n| Participant | Blue Room Score | Orange Room Score | Difference ($X_{iB} - X_{iO}$) |\n|:--------------:|:--------------:|:--------------:|:------------------------:|\n|      1      |        3        |         6         |               -3               |\n|      2      |        9        |         9         |               0                |\n|      3      |        2        |        10         |               -8               |\n|      4      |        9        |         6         |               3                |\n|      5      |        5        |         2         |               3                |\n|      6      |        5        |         7         |               -2               |\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nex1 <- data.frame(\n  id = c(1,2,3,4,5,6),\n  blue = c(3,9,2,9,5,5), \n  orange = c(6,9,10,6,2,7),\n  diff_score = c(-3, 0, -8, 3, 3, -2))\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Determining $t$-crit\n\nCan look things up using a [t-table](https://www.tdistributiontable.com/) where you need the degrees of freedom and the alpha\n\nBut we have R to do those things for us:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#the qt() function is for a 1 tailed test, so we are having to divide it in half to get both tails\nalpha <- 0.05\nn <- nrow(ex1)\nt_crit <- qt(alpha/2, n-1)\nt_crit\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -2.570582\n```\n:::\n:::\n\n\n## Calculating t\n\nLet's get all of the information for the sample we are focusing on (difference scores):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- mean(ex1$diff_score)\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.166667\n```\n:::\n\n```{.r .cell-code}\nsd_diff <- sd(ex1$diff_score)\nsd_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.167333\n```\n:::\n:::\n\n\n## Calculating t\n\nNow we can calculate our $t$-statistic: $$t_{df=n-1} = \\frac{\\bar{D}}{\\frac{sd_{diff}}{\\sqrt{n}}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_stat <- d/(sd_diff/(sqrt(n)))\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.6857474\n```\n:::\n\n```{.r .cell-code}\n#Probability of this t-statistic \np_val <- pt(t_stat, n-1)*2\np_val\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5233677\n```\n:::\n:::\n\n\n## Make a decision\n\nHypotheses:\n\n::: nonincremental\n-   $H_0:$ There is no difference in ratings of happiness between the rooms ( $\\mu = 0$ )\n\n-   $H_1:$ There is a difference in ratings of happiness between the rooms ( $\\mu \\neq 0$ )\n:::\n\n| $alpha$ |          $t-crit$          |    $t-statistic$     |      $p-value$      |\n|:--------------:|:---------------------:|:----------------:|:---------------:|\n|  0.05   | $\\pm$ -2.57 | -0.69 | 0.52 |\n\n**What can we conclude??**\n\n# Example 2: Data in R\n\nWe will use the same dataset that we have in the last few classes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_school <- import(\"https://raw.githubusercontent.com/dharaden/dharaden.github.io/main/courses/PSYC640_fall23/data/NM-NY_CAS.csv\")\n```\n:::\n\n\n## Let's Look at the data\n\nResearch Question: Is there a difference between school nights and weekend nights for amount of time slept?\n\nOnly looking at the variables that we are potentially interested in:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_school %>% \n  select(Gender, Ageyears, Sleep_Hours_Schoolnight, Sleep_Hours_Non_Schoolnight) %>% \n  head() #look at first few observations\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Gender Ageyears Sleep_Hours_Schoolnight Sleep_Hours_Non_Schoolnight\n1 Female       16                     8.0                          13\n2   Male       17                     8.0                           9\n3 Female       19                     8.0                           7\n4   Male       17                     8.0                           9\n5   Male       16                     8.5                           5\n6 Female       11                    11.0                          12\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Difference Score\n\n::: {style=\"font-size: 30px\"}\nThis can be done in a couple different ways and sometimes you will see things computed this way:\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_school$sleep_diff <- state_school$Sleep_Hours_Schoolnight - state_school$Sleep_Hours_Non_Schoolnight\n```\n:::\n\n\n::: {style=\"font-size: 30px\"}\nHowever, we like the `tidyverse` so why don't we use the `mutate()` function\n\nAnd I always overdo things, so I am going to make a new dataset that only has the variables that I'm interested in (`sleep_state_school`)\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsleep_state_school <- state_school %>% \n  mutate(sleep_diff = Sleep_Hours_Schoolnight - Sleep_Hours_Non_Schoolnight) %>%\n  select(Gender, Ageyears, Sleep_Hours_Schoolnight,\n         Sleep_Hours_Non_Schoolnight, sleep_diff)\n\nhead(sleep_state_school)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Gender Ageyears Sleep_Hours_Schoolnight Sleep_Hours_Non_Schoolnight\n1 Female       16                     8.0                          13\n2   Male       17                     8.0                           9\n3 Female       19                     8.0                           7\n4   Male       17                     8.0                           9\n5   Male       16                     8.5                           5\n6 Female       11                    11.0                          12\n  sleep_diff\n1       -5.0\n2       -1.0\n3        1.0\n4       -1.0\n5        3.5\n6       -1.0\n```\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Visualizing\n\nNow that we have our variable of interest, let's take a look at it!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_state_school %>%\n  ggplot(aes(sleep_diff)) + \n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](08_ComparingMeans2_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n## Doing the test in R: One Sample\n\nSince we have calculated the difference scores, we can basically just do a one-sample t-test with the `lsr` library\n\n\n::: {.cell}\n\n```{.r .cell-code}\noneSampleTTest(sleep_state_school$sleep_diff, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   One sample t-test \n\nData variable:   sleep_state_school$sleep_diff \n\nDescriptive statistics: \n            sleep_diff\n   mean         -1.866\n   std dev.      2.741\n\nHypotheses: \n   null:        population mean equals 0 \n   alternative: population mean not equal to 0 \n\nTest results: \n   t-statistic:  -9.106 \n   degrees of freedom:  178 \n   p-value:  <.001 \n\nOther information: \n   two-sided 95% confidence interval:  [-2.27, -1.462] \n   estimated effect size (Cohen's d):  0.681 \n```\n:::\n:::\n\n\n## Doing the test in R: Paired Sample\n\nMaybe we want to keep things separate and don't want to calculate separate values. We can use `pairedSamplesTTest()` instead!\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairedSamplesTTest(\n  formula = ~ Sleep_Hours_Schoolnight + Sleep_Hours_Non_Schoolnight, \n  data = sleep_state_school\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Paired samples t-test \n\nVariables:  Sleep_Hours_Schoolnight , Sleep_Hours_Non_Schoolnight \n\nDescriptive statistics: \n            Sleep_Hours_Schoolnight Sleep_Hours_Non_Schoolnight difference\n   mean                       6.992                       8.858     -1.866\n   std dev.                   1.454                       2.412      2.741\n\nHypotheses: \n   null:        population means equal for both measurements\n   alternative: different population means for each measurement\n\nTest results: \n   t-statistic:  -9.106 \n   degrees of freedom:  178 \n   p-value:  <.001 \n\nOther information: \n   two-sided 95% confidence interval:  [-2.27, -1.462] \n   estimated effect size (Cohen's d):  0.681 \n```\n:::\n:::\n\n\n## Doing the test in R: Classic Edition\n\nAs you Google around to figure things out, you will likely see folks using \\`t.test()\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(\n  x = sleep_state_school$Sleep_Hours_Schoolnight, \n  y = sleep_state_school$Sleep_Hours_Non_Schoolnight, \n  paired = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  sleep_state_school$Sleep_Hours_Schoolnight and sleep_state_school$Sleep_Hours_Non_Schoolnight\nt = -9.1062, df = 178, p-value < 0.00000000000000022\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -2.270281 -1.461563\nsample estimates:\nmean difference \n      -1.865922 \n```\n:::\n:::\n\n\n## Reporting $t$-test\n\nThe first sentence usually conveys some descriptive information about the sample you were comparing (e.g., pre & post test).\n\nThen you identify the type of test you conducted and what was determined (be sure to include the \"stat block\" here as well with the t-statistic, df, p-value, CI and Effect size).\n\nFinish it up by putting that into person words and saying what that means.\n\n# Common Mistakes and Pitfalls\n\n-   **Misinterpreting p-Values**\n\n-   **Violations of Assumptions**\n\n-   **Sample Size Considerations**\n\n-   **Multiple Testing Issues**\n\n------------------------------------------------------------------------\n\n## If we have time: Example 3 - Dog Training\n\nA dog trainer wants to know if dogs are faster at an agility course if a jump is early in the course or later. She has a sample of dogs from her classes run both courses and measures their finish times. Half the class runs the early barrier version on Tuesday, half the class runs the early barrier version on Thursday. Is there a significant difference between course types (alpha = 0.05)?\n\n# Next time...\n\n-   Visualizing with ggplot\n\n-   Parameterization of reports (not using \"magic numbers\")\n",
    "supporting": [
      "08_ComparingMeans2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    // dispatch for htmlwidgets\r\n    function fireSlideEnter() {\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n    }\r\n\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n      fireSlideEnter();\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}